parameters:
    swiftmailer.mailer.db_spool_mailer.spool.enabled: true

services:
    oro_notification.entity_spool:
        class: Oro\Bundle\NotificationBundle\Doctrine\EntityPool
        public: false

    oro_notification.form.type.email_notification:
        class: Oro\Bundle\NotificationBundle\Form\Type\EmailNotificationType
        arguments:
            - '@oro_email.form.subscriber.emailtemplate'
            - '@oro_notification.form.subscriber.additional_emails'
            - '@router'
            - '@oro_notification.form.subscriber.contact_information_emails'
        tags:
            - { name: form.type, alias: emailnotification }

    oro_notification.form.type.recipient_list:
        class: Oro\Bundle\NotificationBundle\Form\Type\RecipientListType
        tags:
            - { name: form.type, alias: oro_notification_recipient_list }

    oro_notification.form.handler.email_notification:
        class: Oro\Bundle\NotificationBundle\Form\Handler\EmailNotificationHandler
        arguments:
            - '@doctrine'
        tags:
            - { name: oro_form.form.handler, alias: oro_notification.form.handler.email_notification }

    oro_notification.form.type.email_notification_entity_choice:
        class: Oro\Bundle\NotificationBundle\Form\Type\EmailNotificationEntityChoiceType
        arguments:
            - '@oro_notification.email_notification_entity_provider'
        tags:
            - { name: form.type, alias: oro_email_notification_entity_choice }

    oro_notification.form.subscriber.additional_emails:
        class: Oro\Bundle\NotificationBundle\Form\EventListener\AdditionalEmailsSubscriber
        public: false
        arguments:
            - '@doctrine'
            - '@translator'
            - '@oro_entity_config.config_manager'

    oro_notification.email_notification.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - 'Oro\Bundle\NotificationBundle\Entity\EmailNotification'
            - '@doctrine.orm.entity_manager'

    oro_notification.doctrine.event.listener:
        class: Oro\Bundle\NotificationBundle\Provider\DoctrineListener
        public: false
        arguments:
            - '@oro_notification.entity_spool'
            - '@event_dispatcher'
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: postFlush }

    oro_notification.manager:
        class: Oro\Bundle\NotificationBundle\Provider\NotificationManager
        arguments:
            - [] # handler service ids sorted by priority. They are set by Oro\Bundle\NotificationBundle\DependencyInjection\Compiler\NotificationHandlerPass
            - '@oro_notification.handler_locator'
            - '@oro_notification.cache'
            - '@doctrine'

    oro_notification.handler_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        public: false
        arguments:
            - [] # handlers. They are set by Oro\Bundle\NotificationBundle\DependencyInjection\Compiler\NotificationHandlerPass
        tags:
            - { name: container.service_locator }

    oro_notification.cache:
        parent: oro.cache.abstract
        public: false
        calls:
            - [ setNamespace, ['oro_notification'] ]

    oro_notification.event_listener.invalidate_cache_listener:
        class: Oro\Bundle\NotificationBundle\EventListener\InvalidateCacheListener
        public: false
        arguments:
            - '@oro_notification.manager'
        tags:
            - { name: doctrine.event_listener, event: onFlush, priority: -255 }
            - { name: doctrine.event_listener, event: postFlush, priority: -255 }

    oro_notification.mass_notification_sender:
        class: Oro\Bundle\NotificationBundle\Model\MassNotificationSender
        arguments:
            - '@oro_notification.manager.email_notification'
            - '@oro_notification.model.notification_settings'
            - '@doctrine'
            - '@oro_notification.entity_spool'

    oro_notification.model.notification_settings:
        class: Oro\Bundle\NotificationBundle\Model\NotificationSettings
        public: false
        arguments:
            - '@oro_config.manager'

    oro_notification.email_handler:
        class: Oro\Bundle\NotificationBundle\Event\Handler\EmailNotificationHandler
        public: false
        arguments:
            - '@oro_notification.manager.email_notification'
            - '@doctrine'
            - '@property_accessor'
            - '@event_dispatcher'
        tags:
            - { name: notification.handler, alias: email_notification_handler }

    oro_notification.mailer.spool_db:
        class: Oro\Bundle\NotificationBundle\Provider\Mailer\DbSpool
        public: false
        arguments:
            - '@doctrine'
            - '@oro_notification.entity_spool'
            - '@event_dispatcher'

    oro_notification.mailer.transport.eventdispatcher:
        parent: swiftmailer.transport.eventdispatcher.abstract
        public: false

    oro_notification.mailer.transport:
        parent: swiftmailer.transport.spool.abstract
        public: false
        arguments:
            - '@oro_notification.mailer.transport.eventdispatcher'
            - '@oro_notification.mailer.spool_db'

    swiftmailer.mailer.db_spool_mailer:
        class: '%swiftmailer.class%'
        public: false
        arguments:
            - '@oro_notification.mailer.transport'

    swiftmailer.mailer.db_spool_mailer.transport.real:
        alias: swiftmailer.transport.real

    oro_notification.grid_helper:
        class: Oro\Bundle\NotificationBundle\Provider\EmailNotificationGridHelper
        arguments:
            - '@doctrine'

    oro_notification.email_notification_entity_provider:
        class: Oro\Bundle\NotificationBundle\Provider\EmailNotificationEntityProvider
        parent: oro_entity.entity_provider.abstract
        public: false
        arguments:
            - '@doctrine'

    oro_notification.event_listener.mass_notification_log:
        class: Oro\Bundle\NotificationBundle\EventListener\MassNotificationListener
        arguments:
            - '@doctrine'
        tags:
            - { name: kernel.event_listener, event: oro.notification.event.notification_send_after, method: logMassNotification}

    oro_notification.mailer.mass_email_direct_mailer:
        class: Oro\Bundle\NotificationBundle\Mailer\MassEmailDirectMailer
        public: false
        arguments:
            - '@oro_email.direct_mailer'
            - '@event_dispatcher'

    oro_notification.manager.template_email.mass:
        class: Oro\Bundle\EmailBundle\Manager\TemplateEmailManager
        public: false
        arguments:
            - '@oro_notification.mailer.mass_email_direct_mailer'
            - '@oro_locale.provider.chain_preferred_language_provider'
            - '@oro_email.mailer.processor'
            - '@oro_email.provider.email_template_content_provider'

    oro_notification.async.template_email_message_sender.mass:
        class: Oro\Bundle\EmailBundle\Async\TemplateEmailMessageSender
        public: false
        arguments:
            - '@oro_notification.manager.template_email.mass'
            - '@oro_entity.doctrine_helper'

    oro_notification.async.send_email_message_processor:
        class: Oro\Bundle\NotificationBundle\Async\SendEmailMessageProcessor
        arguments:
            - '@oro_email.direct_mailer'
            - '@oro_email.mailer.processor'
            - '@doctrine'
            - '@oro_email.email_renderer'
            - '@logger'
            - '@oro_email.async.template_email_message_sender'
        tags:
            - { name: 'oro_message_queue.client.message_processor', topicName: oro.notification.send_notification_email }

    oro_notification.async.send_mass_email_message_processor:
        class: Oro\Bundle\NotificationBundle\Async\SendMassEmailMessageProcessor
        arguments:
            - '@oro_email.direct_mailer'
            - '@oro_email.mailer.processor'
            - '@doctrine'
            - '@oro_email.email_renderer'
            - '@logger'
            - '@event_dispatcher'
            - '@oro_notification.async.template_email_message_sender.mass'
        tags:
            - { name: 'oro_message_queue.client.message_processor', topicName: oro.notification.send_mass_notification_email }

    oro_notification.manager.email_notification:
        class: Oro\Bundle\NotificationBundle\Manager\EmailNotificationManager
        arguments:
            - '@oro_notification.manager.email_notification_sender'
            - '@logger'
            - '@oro_email.provider.email_template_content_provider'
            - '@oro_locale.provider.chain_preferred_language_provider'

    oro_notification.manager.email_notification_sender:
        class: Oro\Bundle\NotificationBundle\Manager\EmailNotificationSender
        public: false
        arguments:
            - '@oro_notification.model.notification_settings'
            - '@oro_message_queue.client.message_producer'

    oro_notification.provider.contact_information_emails:
        class: Oro\Bundle\NotificationBundle\Provider\ContactInformationEmailsProvider
        public: false
        arguments:
            - '@oro_entity_config.config_manager'
            - '@translator'

    oro_notification.form.subscriber.contact_information_emails:
        class: Oro\Bundle\NotificationBundle\Form\EventListener\ContactInformationEmailsSubscriber
        public: false
        arguments:
            - '@oro_notification.provider.contact_information_emails'

    oro_notification.provider.email_address_with_context_preferred_language_provider:
        class: Oro\Bundle\NotificationBundle\Provider\EmailAddressWithContextPreferredLanguageProvider
        public: false
        arguments:
            - '@oro_locale.provider.chain_preferred_language_provider'
        tags:
            - { name: oro_locale.preferred_language_provider, priority: -255 }
