parameters:
    oro_theme.registry.class: Oro\Bundle\ThemeBundle\Model\ThemeRegistry

services:
    oro_theme.registry:
        class: '%oro_theme.registry.class%'
        arguments:
            - '%oro_theme.settings%'

    oro_theme.twig.extension:
        class: Oro\Bundle\ThemeBundle\Twig\ThemeExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }
